lint-error:
  - any: ["src/*.js, utils/*.js"]

utils:
  - any: ["utils/*.js"]

src:
  - any: ["src/*.js"]

docs:
  - any: ["docs/*.md", "**/*.md"]

ci:
  - any: [".github/*.yml", ".github/workflows/*.yml"]