name: "Pull Request Labeler"
on:
# - pull_request_target
  pull_request_target:
    branches: [master]
  workflow_run:
    workflows: [Lint Check]
    types: [completed]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      # with:
      #   repo-token: ${{ github.repository.token }}