name: Lint Check
on:
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check-lint
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ github.token }}

  on-failure:
    permissions: write-all
    name: on-failure
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ always() && contains(needs.*.result, 'failure') && github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v3
        with:
          name: pr_num
          path: ./pr_num.txt